version: '3.8'

services:
  # Сервер Фронтенда
  frontend:
    build: ./client
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_PORT=5000

  # Сервер Бэкенда
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://peta:docker_password@db:5432/my_deploy_db
      - PORT=3000
    depends_on:
      - db

  # База данных
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: peta
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: my_deploy_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: